name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Load Environment Variables
        run: |
          echo "CYPRESS_API_URL=${{ secrets.CYPRESS_API_URL }}" >> $GITHUB_ENV
          echo "CYPRESS_API_KEY=${{ secrets.CYPRESS_API_KEY }}" >> $GITHUB_ENV

      - name: Run Cypress Tests
        run: npm run test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/videos/

      - name: Notify of Test Failures
        if: failure()
        run: echo "Tests failed. Check the Cypress results for more details."